name: "Hit a webhook"
 
on:
  push:
    tags:
      - '**'
 
jobs:
  run-updater:
    runs-on: ubuntu-latest
    steps:
    - name: REST API with curl
      run: |
        curl -X GET "https://learn.microsoft.com/en-us/azure/devops/cross-service/cross-service-overview?view=azure-devops"
