name: "Hit a webhook"
 
on: [push]
 
jobs:
  run-updater:
    runs-on: ubuntu-latest
    steps:
    - name: REST API with curl
      uses: azzarb/curl-demo-with-postman@main
    - run: |
        curl -X GET "https://ralphjsmit.com/api-endpoint-webhook-github-actions"
