name: "Hit a webhook"
 
on: [push]
 
jobs:
  run-updater:
    runs-on: ubuntu-latest
    steps:
    - name: REST API with curl
      shell: bash
      run: |
       # curl -X GET "https://ralphjsmit.com/api-endpoint-webhook-github-actions"
       curl -X GET "https://api.github.com/users/azzarb/repos" > ./getdata.json
       # jq -r '.' getdata.json
       # jq -r '.[1]' getdata.json
       # jq -r '.[] | .id ' getdata.json
       # jq -r '.[0] | .id, .full_name' getdata.json
       # jq -r '.[1] | .owner .id' getdata.json
       # jq -r '.[2] | .id ' getdata.json
       #jq -r '.[2] | .owner .id' getdata.json
       #jq -r '.[2] | .owner .login' getdata.json
       jq -r '.[] | .name' getdata.json
       jq -r '.[] | .owner .url' getdata.json
      
    

